name: nginx_proxy

services:
  nginx:
    image: nginx:alpine
    container_name: zeze_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs/patients:/etc/nginx/certs/patients:ro
      - ./nginx/certs/cisse:/etc/nginx/certs/cisse:ro
      - ./nginx/certs/alice:/etc/nginx/certs/alice:ro
    networks:
      - zeze_proxy

networks:
  zeze_proxy:
    external: true
