name: nginx_proxy

services:
  nginx:
    image: nginx:alpine
    container_name: zeze_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - zeze_proxy

networks:
  zeze_proxy:
    external: true
