FROM node:20-alpine

WORKDIR /app

# Installation de nodemon globalement pour le hot reload
RUN npm install -g nodemon

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
